// Code generated by Kitex v0.9.1. DO NOT EDIT.

package followhandler

import (
	follow "bibi/kitex_gen/follow"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowAction(ctx context.Context, req *follow.FollowActionRequest, callOptions ...callopt.Option) (r *follow.FollowActionResponse, err error)
	FollowerList(ctx context.Context, req *follow.FollowerListRequest, callOptions ...callopt.Option) (r *follow.FollowerListResponse, err error)
	FollowingList(ctx context.Context, req *follow.FollowingListRequest, callOptions ...callopt.Option) (r *follow.FollowingListResponse, err error)
	FriendList(ctx context.Context, req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kFollowHandlerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFollowHandlerClient struct {
	*kClient
}

func (p *kFollowHandlerClient) FollowAction(ctx context.Context, req *follow.FollowActionRequest, callOptions ...callopt.Option) (r *follow.FollowActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowAction(ctx, req)
}

func (p *kFollowHandlerClient) FollowerList(ctx context.Context, req *follow.FollowerListRequest, callOptions ...callopt.Option) (r *follow.FollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerList(ctx, req)
}

func (p *kFollowHandlerClient) FollowingList(ctx context.Context, req *follow.FollowingListRequest, callOptions ...callopt.Option) (r *follow.FollowingListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowingList(ctx, req)
}

func (p *kFollowHandlerClient) FriendList(ctx context.Context, req *follow.FriendListRequest, callOptions ...callopt.Option) (r *follow.FriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FriendList(ctx, req)
}
