// Code generated by Kitex v0.9.1. DO NOT EDIT.

package followhandler

import (
	follow "bibi/kitex_gen/follow"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"FollowAction": kitex.NewMethodInfo(
		followActionHandler,
		newFollowHandlerFollowActionArgs,
		newFollowHandlerFollowActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowerList": kitex.NewMethodInfo(
		followerListHandler,
		newFollowHandlerFollowerListArgs,
		newFollowHandlerFollowerListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FollowingList": kitex.NewMethodInfo(
		followingListHandler,
		newFollowHandlerFollowingListArgs,
		newFollowHandlerFollowingListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FriendList": kitex.NewMethodInfo(
		friendListHandler,
		newFollowHandlerFriendListArgs,
		newFollowHandlerFriendListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	followHandlerServiceInfo                = NewServiceInfo()
	followHandlerServiceInfoForClient       = NewServiceInfoForClient()
	followHandlerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return followHandlerServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return followHandlerServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return followHandlerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "FollowHandler"
	handlerType := (*follow.FollowHandler)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "follow",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func followActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*follow.FollowHandlerFollowActionArgs)
	realResult := result.(*follow.FollowHandlerFollowActionResult)
	success, err := handler.(follow.FollowHandler).FollowAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFollowActionArgs() interface{} {
	return follow.NewFollowHandlerFollowActionArgs()
}

func newFollowHandlerFollowActionResult() interface{} {
	return follow.NewFollowHandlerFollowActionResult()
}

func followerListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*follow.FollowHandlerFollowerListArgs)
	realResult := result.(*follow.FollowHandlerFollowerListResult)
	success, err := handler.(follow.FollowHandler).FollowerList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFollowerListArgs() interface{} {
	return follow.NewFollowHandlerFollowerListArgs()
}

func newFollowHandlerFollowerListResult() interface{} {
	return follow.NewFollowHandlerFollowerListResult()
}

func followingListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*follow.FollowHandlerFollowingListArgs)
	realResult := result.(*follow.FollowHandlerFollowingListResult)
	success, err := handler.(follow.FollowHandler).FollowingList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFollowingListArgs() interface{} {
	return follow.NewFollowHandlerFollowingListArgs()
}

func newFollowHandlerFollowingListResult() interface{} {
	return follow.NewFollowHandlerFollowingListResult()
}

func friendListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*follow.FollowHandlerFriendListArgs)
	realResult := result.(*follow.FollowHandlerFriendListResult)
	success, err := handler.(follow.FollowHandler).FriendList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFollowHandlerFriendListArgs() interface{} {
	return follow.NewFollowHandlerFriendListArgs()
}

func newFollowHandlerFriendListResult() interface{} {
	return follow.NewFollowHandlerFriendListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FollowAction(ctx context.Context, req *follow.FollowActionRequest) (r *follow.FollowActionResponse, err error) {
	var _args follow.FollowHandlerFollowActionArgs
	_args.Req = req
	var _result follow.FollowHandlerFollowActionResult
	if err = p.c.Call(ctx, "FollowAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowerList(ctx context.Context, req *follow.FollowerListRequest) (r *follow.FollowerListResponse, err error) {
	var _args follow.FollowHandlerFollowerListArgs
	_args.Req = req
	var _result follow.FollowHandlerFollowerListResult
	if err = p.c.Call(ctx, "FollowerList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FollowingList(ctx context.Context, req *follow.FollowingListRequest) (r *follow.FollowingListResponse, err error) {
	var _args follow.FollowHandlerFollowingListArgs
	_args.Req = req
	var _result follow.FollowHandlerFollowingListResult
	if err = p.c.Call(ctx, "FollowingList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FriendList(ctx context.Context, req *follow.FriendListRequest) (r *follow.FriendListResponse, err error) {
	var _args follow.FollowHandlerFriendListArgs
	_args.Req = req
	var _result follow.FollowHandlerFriendListResult
	if err = p.c.Call(ctx, "FriendList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
