// Code generated by hertz generator.

package api

import (
	"context"

	api "bibi/api/biz/model/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PutVideo .
// @router /bibi/video/upload [POST]
func PutVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PutVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.PutVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListVideo .
// @router /bibi/video/published [GET]
func ListVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.ListUserVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.ListUserVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router /bibi/video/search [POST]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.SearchVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.SearchVideoResponse)

	c.JSON(consts.StatusOK, resp)
}

// HotVideo .
// @router /bibi/video/hot [GET]
func HotVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.HotVideoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.HotVideoResponse)

	c.JSON(consts.StatusOK, resp)
}
