version: '3.7'

networks:
  bibi:
    driver: bridge

services:
  mysql:
    image: mysql:8.0.36
#    image: registry.cn-hangzhou.aliyuncs.com/fanr/mysql:8.0.36
    container_name: bibi
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_DATABASE=bibi_db
      - MYSQL_ROOT_PASSWORD=114514
      - TZ=Asia/Shanghai
    security_opt:
      - seccomp:unconfined
    restart: always
    networks:
      - bibi
  redis:
    image: redis:6.0.16
    container_name: redis
    ports:
      - "6399:6379"
    volumes:
      - ./data/redis/data:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/logs:/logs
    restart: always
    networks:
      - bibi

  etcd:
    image: bitnami/etcd:3.5
#    image: registry.cn-hangzhou.aliyuncs.com/fanr/etcd:3.5
    container_name: etcd
    ports:
      - "2389:2379"
      - "2390:2380"
    volumes:
      - ./data/etcd/data:/bitnami/etcd-data
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - bibi

  nacos:
#    如果哪天连不上了，就是env里mysqlIP要改了，傻逼校园网
    image: nacos/nacos-server:v2.3.2
#    image: registry.cn-hangzhou.aliyuncs.com/fanr/nacos-server:v2.3.2
    container_name: nacos
    env_file:
      - ./config/nacos/nacos-standlone-mysql.env
    volumes:
      - ./data/nacos/standalone-logs/:/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    network_mode: host
#    networks:
#      - bibi

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 20M
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m" # 加大内存设置
      discovery.type: single-node
      TZ: Asia/Shanghai
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./config/elasticsearch/config:/usr/share/elasticsearch/config
      - ./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always
    networks:
      - bibi

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana:/usr/share/kibana/config
      - ./data/kibana:/usr/share/kibana/data
    networks:
      - bibi

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
    network_mode: host

#  hotrod:
#    image: jaegertracing/example-hotrod:latest
#    container_name: hotrod
#    restart: always
#    ports:
#      - "8080:8080"
#      - "8083:8083"
#    command: [ "all", "--otel-exporter=otlp" ]
#    environment:
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
#    network_mode: host
#    depends_on:
#      - jaeger
#  rabbitmq:
#    image: rabbitmq:management
#    container_name: rabbitmq
#    hostname: rabbit
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      TZ: Asia/Shanghai
#      RABBITMQ_DEFAULT_USER: bibi
#      RABBITMQ_DEFAULT_PASS: bibi
#    restart: always
#    volumes:
#      - ./data/rabbitmq:/var/lib/rabbitmq
#      - ./config/rabbitmq:/etc/rabbitmq
#    networks:
#      - bibi
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
#    image: registry.cn-hangzhou.aliyuncs.com/fanr/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - bibi

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.4
#    image: registry.cn-hangzhou.aliyuncs.com/fanr/milvus:v2.4.4
    command: [ "milvus", "run", "standalone" ]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./data/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - bibi