// Code generated by Kitex v0.9.1. DO NOT EDIT.

package videohandler

import (
	video "bibi/kitex_gen/video"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PutVideo(ctx context.Context, req *video.PutVideoRequest, callOptions ...callopt.Option) (r *video.PutVideoResponse, err error)
	ListVideo(ctx context.Context, req *video.ListUserVideoRequest, callOptions ...callopt.Option) (r *video.ListUserVideoResponse, err error)
	SearchVideo(ctx context.Context, req *video.SearchVideoRequest, callOptions ...callopt.Option) (r *video.SearchVideoResponse, err error)
	HotVideo(ctx context.Context, req *video.HotVideoRequest, callOptions ...callopt.Option) (r *video.HotVideoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoHandlerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoHandlerClient struct {
	*kClient
}

func (p *kVideoHandlerClient) PutVideo(ctx context.Context, req *video.PutVideoRequest, callOptions ...callopt.Option) (r *video.PutVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PutVideo(ctx, req)
}

func (p *kVideoHandlerClient) ListVideo(ctx context.Context, req *video.ListUserVideoRequest, callOptions ...callopt.Option) (r *video.ListUserVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListVideo(ctx, req)
}

func (p *kVideoHandlerClient) SearchVideo(ctx context.Context, req *video.SearchVideoRequest, callOptions ...callopt.Option) (r *video.SearchVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchVideo(ctx, req)
}

func (p *kVideoHandlerClient) HotVideo(ctx context.Context, req *video.HotVideoRequest, callOptions ...callopt.Option) (r *video.HotVideoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HotVideo(ctx, req)
}
