# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: picture.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='picture.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\010./vector',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rpicture.proto\"!\n\x10GetVectorRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"#\n\x11GetVectorResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32\x43\n\x06Vector\x12\x39\n\x10GetPictureVector\x12\x11.GetVectorRequest\x1a\x12.GetVectorResponseB\nZ\x08./vectorb\x06proto3'
)




_GETVECTORREQUEST = _descriptor.Descriptor(
  name='GetVectorRequest',
  full_name='GetVectorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='GetVectorRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=50,
)


_GETVECTORRESPONSE = _descriptor.Descriptor(
  name='GetVectorResponse',
  full_name='GetVectorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='vector', full_name='GetVectorResponse.vector', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['GetVectorRequest'] = _GETVECTORREQUEST
DESCRIPTOR.message_types_by_name['GetVectorResponse'] = _GETVECTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetVectorRequest = _reflection.GeneratedProtocolMessageType('GetVectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETVECTORREQUEST,
  '__module__' : 'picture_pb2'
  # @@protoc_insertion_point(class_scope:GetVectorRequest)
  })
_sym_db.RegisterMessage(GetVectorRequest)

GetVectorResponse = _reflection.GeneratedProtocolMessageType('GetVectorResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETVECTORRESPONSE,
  '__module__' : 'picture_pb2'
  # @@protoc_insertion_point(class_scope:GetVectorResponse)
  })
_sym_db.RegisterMessage(GetVectorResponse)


DESCRIPTOR._options = None

_VECTOR = _descriptor.ServiceDescriptor(
  name='Vector',
  full_name='Vector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=89,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPictureVector',
    full_name='Vector.GetPictureVector',
    index=0,
    containing_service=None,
    input_type=_GETVECTORREQUEST,
    output_type=_GETVECTORRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VECTOR)

DESCRIPTOR.services_by_name['Vector'] = _VECTOR

# @@protoc_insertion_point(module_scope)
