info:
  contact: {}
paths:
  /bibi/access_token/get:
    get:
      consumes:
      - json/form
      description: get available access-token by refresh-token
      parameters:
      - description: refresh-token
        in: header
        name: refresh-token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: get_access-token
  /bibi/interaction/comment/create:
    post:
      consumes:
      - json/form
      description: comment video
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 父评论id
        in: query
        name: parent_id
        type: integer
      - description: 正文
        in: query
        name: content
        required: true
        type: string
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_create
  /bibi/interaction/comment/delete:
    post:
      consumes:
      - json/form
      description: delete your comment
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 评论id
        in: query
        name: comment_id
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_delete
  /bibi/interaction/comment/list:
    post:
      consumes:
      - json/form
      description: show video's comments
      parameters:
      - description: 视频id
        in: query
        name: video_id
        required: true
        type: integer
      - description: 页码
        in: query
        name: page_num
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: comment_list
  /bibi/interaction/like/action:
    post:
      consumes:
      - json/form
      description: like or dislike video
      parameters:
      - description: 视频id
        in: query
        name: video_id
        type: integer
      - description: 评论id
        in: query
        name: comment_id
        type: integer
      - description: 点赞:0;取消点赞:1
        in: query
        name: action_type
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: like_action
  /bibi/interaction/like/list:
    get:
      consumes:
      - json/form
      description: show the list of your liked videos
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: like_list
  /bibi/user/avatar/upload:
    put:
      consumes:
      - json/form
      description: revise user's avatar
      parameters:
      - description: 头像
        in: formData
        name: avatar_file
        required: true
        type: file
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: PutAvatar
  /bibi/user/info:
    get:
      consumes:
      - json/form
      description: get user's info
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: Info
  /bibi/user/login/:
    post:
      consumes:
      - json/form
      description: login to get your auth token
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      - description: otp
        in: query
        name: otp
        type: string
      produces:
      - application/json
      responses: {}
      summary: Login
  /bibi/user/register/:
    post:
      consumes:
      - json/form
      description: userRegister
      parameters:
      - description: 用户名
        in: query
        name: username
        required: true
        type: string
      - description: 邮箱
        in: query
        name: email
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Register
  /bibi/user/switch2fa:
    post:
      consumes:
      - json/form
      description: switch on/off 2fa mode
      parameters:
      - description: 关闭:0;开启:1
        in: query
        name: action_type
        required: true
        type: integer
      - description: totp
        in: query
        name: totp
        type: string
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: switch_2fa
  /bibi/video/hot:
    get:
      responses: {}
  /bibi/video/published:
    get:
      consumes:
      - json/form
      description: list user's videos
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: ListVideo
  /bibi/video/search:
    post:
      consumes:
      - json/form
      description: search videos
      parameters:
      - description: 页码
        in: query
        name: page_num
        required: true
        type: integer
      - description: 搜索内容
        in: query
        name: param
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: SearchVideo
  /bibi/video/upload:
    post:
      consumes:
      - json/form
      description: put video
      parameters:
      - description: 视频文件
        in: formData
        name: video_file
        required: true
        type: file
      - description: 标题
        in: query
        name: title
        required: true
        type: string
      - description: 视频封面
        in: formData
        name: cover
        required: true
        type: file
      - description: access-token
        in: header
        name: access-token
        type: string
      - description: refresh-token
        in: header
        name: refresh-token
        type: string
      produces:
      - application/json
      responses: {}
      summary: PutVideo
swagger: "2.0"
