server:
  jwt-secret: exceed gear
  version: "debug"
  name: bibi

etcd:
  addr: 127.0.0.1:2379

mysql:
  addr: 127.0.0.1:3366
  user: root
  password: 114514
  database: bibi_db

redis:
  addr: 127.0.0.1:6399

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accesskeyid:
  accesskeysecret:
  bucketname:
  main-directory:


rabbitmq:
  addr: 127.0.0.1:5672
  user: guest
  password: guest

email:
  host: smtp.qq.com
  port: 25
  sender:
  password:
  from:
  subject: 您 Steam 愿望单上的 《天使☆纷扰 RE-BOOT!》无法购买！

elasticsearch:
  addr: 127.0.0.1:9200
  host: 127.0.0.1

services:
  api:
    name: api
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    addr:
      - 127.0.0.1:10002
  chat:
    name: chat
    addr:
      - 127.0.0.1:10003
  follow:
    name: follow
    addr:
      - 127.0.0.1:10004
  interaction:
    name: interaction
    addr:
      - 127.0.0.1:10005
  video:
    name: video
    addr:
      - 127.0.0.1:10006