server:
  jwt-secret: exceed gear
  version: "debug"
  name: bibi

etcd:
  addr: 127.0.0.1:2379

mysql:
  addr: 127.0.0.1:3366
  user: root
  password: 114514
  database: bibi_db

redis:
  addr: 127.0.0.1:6399

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  accesskeyid: LTAI5tLxvgGfKqWqUc7t9mLe
  accesskeysecret: 4h6MoIFctgbciZW19qwnup7IYUqxwz
  bucketname: bibi-demo
  main-directory: bibi


rabbitmq:
  addr: 127.0.0.1:5672
  user: guest
  password: guest

email:
  host: smtp.qq.com
  port: 25
  sender: 2875007734@qq.com
  password: zlqgfvscdhpvdged
  from: bibi-demo<2875007734@qq.com>
  subject: 您 Steam 愿望单上的 《天使☆纷扰 RE-BOOT!》无法购买！

services:
  api:
    name: api
    load-balance: false
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    load-balance: false
    addr:
      - 127.0.0.1:10002
  chat:
    name: chat
    load-balance: false
    addr:
      - 127.0.0.1:10003
  follow:
    name: follow
    load-balance: false
    addr:
      - 127.0.0.1:10004
  interaction:
    name: interaction
    load-balance: false
    addr:
      - 127.0.0.1:10005
  video:
    name: video
    load-balance: false
    addr:
      - 127.0.0.1:10006