// Code generated by Kitex v0.9.1. DO NOT EDIT.

package interactionhandler

import (
	interaction "bibi/kitex_gen/interaction"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"LikeAction": kitex.NewMethodInfo(
		likeActionHandler,
		newInteractionHandlerLikeActionArgs,
		newInteractionHandlerLikeActionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"LikeList": kitex.NewMethodInfo(
		likeListHandler,
		newInteractionHandlerLikeListArgs,
		newInteractionHandlerLikeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentCreate": kitex.NewMethodInfo(
		commentCreateHandler,
		newInteractionHandlerCommentCreateArgs,
		newInteractionHandlerCommentCreateResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentDelete": kitex.NewMethodInfo(
		commentDeleteHandler,
		newInteractionHandlerCommentDeleteArgs,
		newInteractionHandlerCommentDeleteResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLikesCountByVideoIdList": kitex.NewMethodInfo(
		getLikesCountByVideoIdListHandler,
		newInteractionHandlerGetLikesCountByVideoIdListArgs,
		newInteractionHandlerGetLikesCountByVideoIdListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetIsLikeByVideoIdList": kitex.NewMethodInfo(
		getIsLikeByVideoIdListHandler,
		newInteractionHandlerGetIsLikeByVideoIdListArgs,
		newInteractionHandlerGetIsLikeByVideoIdListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CommentList": kitex.NewMethodInfo(
		commentListHandler,
		newInteractionHandlerCommentListArgs,
		newInteractionHandlerCommentListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	interactionHandlerServiceInfo                = NewServiceInfo()
	interactionHandlerServiceInfoForClient       = NewServiceInfoForClient()
	interactionHandlerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return interactionHandlerServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return interactionHandlerServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return interactionHandlerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "InteractionHandler"
	handlerType := (*interaction.InteractionHandler)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "interaction",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func likeActionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerLikeActionArgs)
	realResult := result.(*interaction.InteractionHandlerLikeActionResult)
	success, err := handler.(interaction.InteractionHandler).LikeAction(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerLikeActionArgs() interface{} {
	return interaction.NewInteractionHandlerLikeActionArgs()
}

func newInteractionHandlerLikeActionResult() interface{} {
	return interaction.NewInteractionHandlerLikeActionResult()
}

func likeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerLikeListArgs)
	realResult := result.(*interaction.InteractionHandlerLikeListResult)
	success, err := handler.(interaction.InteractionHandler).LikeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerLikeListArgs() interface{} {
	return interaction.NewInteractionHandlerLikeListArgs()
}

func newInteractionHandlerLikeListResult() interface{} {
	return interaction.NewInteractionHandlerLikeListResult()
}

func commentCreateHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerCommentCreateArgs)
	realResult := result.(*interaction.InteractionHandlerCommentCreateResult)
	success, err := handler.(interaction.InteractionHandler).CommentCreate(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerCommentCreateArgs() interface{} {
	return interaction.NewInteractionHandlerCommentCreateArgs()
}

func newInteractionHandlerCommentCreateResult() interface{} {
	return interaction.NewInteractionHandlerCommentCreateResult()
}

func commentDeleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerCommentDeleteArgs)
	realResult := result.(*interaction.InteractionHandlerCommentDeleteResult)
	success, err := handler.(interaction.InteractionHandler).CommentDelete(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerCommentDeleteArgs() interface{} {
	return interaction.NewInteractionHandlerCommentDeleteArgs()
}

func newInteractionHandlerCommentDeleteResult() interface{} {
	return interaction.NewInteractionHandlerCommentDeleteResult()
}

func getLikesCountByVideoIdListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerGetLikesCountByVideoIdListArgs)
	realResult := result.(*interaction.InteractionHandlerGetLikesCountByVideoIdListResult)
	success, err := handler.(interaction.InteractionHandler).GetLikesCountByVideoIdList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerGetLikesCountByVideoIdListArgs() interface{} {
	return interaction.NewInteractionHandlerGetLikesCountByVideoIdListArgs()
}

func newInteractionHandlerGetLikesCountByVideoIdListResult() interface{} {
	return interaction.NewInteractionHandlerGetLikesCountByVideoIdListResult()
}

func getIsLikeByVideoIdListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerGetIsLikeByVideoIdListArgs)
	realResult := result.(*interaction.InteractionHandlerGetIsLikeByVideoIdListResult)
	success, err := handler.(interaction.InteractionHandler).GetIsLikeByVideoIdList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerGetIsLikeByVideoIdListArgs() interface{} {
	return interaction.NewInteractionHandlerGetIsLikeByVideoIdListArgs()
}

func newInteractionHandlerGetIsLikeByVideoIdListResult() interface{} {
	return interaction.NewInteractionHandlerGetIsLikeByVideoIdListResult()
}

func commentListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*interaction.InteractionHandlerCommentListArgs)
	realResult := result.(*interaction.InteractionHandlerCommentListResult)
	success, err := handler.(interaction.InteractionHandler).CommentList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newInteractionHandlerCommentListArgs() interface{} {
	return interaction.NewInteractionHandlerCommentListArgs()
}

func newInteractionHandlerCommentListResult() interface{} {
	return interaction.NewInteractionHandlerCommentListResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) LikeAction(ctx context.Context, req *interaction.LikeActionRequest) (r *interaction.LikeActionResponse, err error) {
	var _args interaction.InteractionHandlerLikeActionArgs
	_args.Req = req
	var _result interaction.InteractionHandlerLikeActionResult
	if err = p.c.Call(ctx, "LikeAction", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LikeList(ctx context.Context, req *interaction.LikeListRequest) (r *interaction.LikeListResponse, err error) {
	var _args interaction.InteractionHandlerLikeListArgs
	_args.Req = req
	var _result interaction.InteractionHandlerLikeListResult
	if err = p.c.Call(ctx, "LikeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentCreate(ctx context.Context, req *interaction.CommentCreateRequest) (r *interaction.CommentCreateResponse, err error) {
	var _args interaction.InteractionHandlerCommentCreateArgs
	_args.Req = req
	var _result interaction.InteractionHandlerCommentCreateResult
	if err = p.c.Call(ctx, "CommentCreate", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentDelete(ctx context.Context, req *interaction.CommentDeleteRequest) (r *interaction.CommentDeleteResponse, err error) {
	var _args interaction.InteractionHandlerCommentDeleteArgs
	_args.Req = req
	var _result interaction.InteractionHandlerCommentDeleteResult
	if err = p.c.Call(ctx, "CommentDelete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLikesCountByVideoIdList(ctx context.Context, req *interaction.GetLikesCountByVideoIdListRequest) (r *interaction.GetLikesCountByVideoIdListResponse, err error) {
	var _args interaction.InteractionHandlerGetLikesCountByVideoIdListArgs
	_args.Req = req
	var _result interaction.InteractionHandlerGetLikesCountByVideoIdListResult
	if err = p.c.Call(ctx, "GetLikesCountByVideoIdList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetIsLikeByVideoIdList(ctx context.Context, req *interaction.GetIsLikeByVideoIdListRequest) (r *interaction.GetIsLikeByVideoIdListResponse, err error) {
	var _args interaction.InteractionHandlerGetIsLikeByVideoIdListArgs
	_args.Req = req
	var _result interaction.InteractionHandlerGetIsLikeByVideoIdListResult
	if err = p.c.Call(ctx, "GetIsLikeByVideoIdList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CommentList(ctx context.Context, req *interaction.CommentListRequest) (r *interaction.CommentListResponse, err error) {
	var _args interaction.InteractionHandlerCommentListArgs
	_args.Req = req
	var _result interaction.InteractionHandlerCommentListResult
	if err = p.c.Call(ctx, "CommentList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
