// Code generated by hertz generator.

package api

import (
	"bibi/cmd/api/biz/mw/jwt"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _bibiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _infoMw() []app.HandlerFunc {
	return nil
}

func _switch2faMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatar0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _login0Mw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.LoginHandler,
	}
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _access_tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getaccesstokenMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtRefreshMiddleware.MiddlewareFunc(),
		//jwt.JwtMiddleware.RefreshToken,
	}
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hotvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _searchvideoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _putvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _interactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentcreateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _commentdeleteMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _commentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _likelistMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _followMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _followerlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _followinglistMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _friendlistMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _messageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _messagerecordMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.JwtMiddleware.MiddlewareFunc(),
	}
}

func _searchavatarMw() []app.HandlerFunc {
	// your code...
	return nil
}
