// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VectorClient is the client API for Vector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorClient interface {
	GetPictureVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error)
}

type vectorClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorClient(cc grpc.ClientConnInterface) VectorClient {
	return &vectorClient{cc}
}

func (c *vectorClient) GetPictureVector(ctx context.Context, in *GetVectorRequest, opts ...grpc.CallOption) (*GetVectorResponse, error) {
	out := new(GetVectorResponse)
	err := c.cc.Invoke(ctx, "/Vector/GetPictureVector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VectorServer is the server API for Vector service.
// All implementations must embed UnimplementedVectorServer
// for forward compatibility
type VectorServer interface {
	GetPictureVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error)
	mustEmbedUnimplementedVectorServer()
}

// UnimplementedVectorServer must be embedded to have forward compatible implementations.
type UnimplementedVectorServer struct {
}

func (UnimplementedVectorServer) GetPictureVector(context.Context, *GetVectorRequest) (*GetVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPictureVector not implemented")
}
func (UnimplementedVectorServer) mustEmbedUnimplementedVectorServer() {}

// UnsafeVectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorServer will
// result in compilation errors.
type UnsafeVectorServer interface {
	mustEmbedUnimplementedVectorServer()
}

func RegisterVectorServer(s grpc.ServiceRegistrar, srv VectorServer) {
	s.RegisterService(&Vector_ServiceDesc, srv)
}

func _Vector_GetPictureVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorServer).GetPictureVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Vector/GetPictureVector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorServer).GetPictureVector(ctx, req.(*GetVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vector_ServiceDesc is the grpc.ServiceDesc for Vector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Vector",
	HandlerType: (*VectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPictureVector",
			Handler:    _Vector_GetPictureVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture.proto",
}
